name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REACT_APP_RECAPTCHA_PUBLIC: ${{ secrets.DOCKER_PASSWORD }}
  REACT_APP_RECAPTCHA_SECRET: ${{ secrets.REACT_APP_RECAPTCHA_SECRET }}
  REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
  REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
  REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
  REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
  REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
  REACT_APP_EMAIL_SERVICE_ID: ${{ secrets.REACT_APP_EMAIL_SERVICE_ID }}
  REACT_APP_EMAIL_TEMPLATE: ${{ secrets.REACT_APP_EMAIL_TEMPLATE }}
  REACT_APP_EMAIL_USER_ID: ${{ secrets.REACT_APP_EMAIL_USER_ID }}

#Each job is run on a new server
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout backend repo
        uses: actions/checkout@v2
        with:
          repository: 7wesley/cards-backend
          path: server
      - name: Install client dependencies
        run: npm ci
      - name: Install server dependencies
        run: npm ci
        working-directory: ./server
      # Run cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
<<<<<<< HEAD
          build: npm run build
          start: npm start
=======
          build: npm build
          start: npm start, npm start --prefix server
          wait-on: 'http://localhost:3000, http://localhost:5000'
>>>>>>> 7582136adb776a7530995416c59254b9453ac038
        
  docker-publish:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
=======
    needs: cypress-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
>>>>>>> 7582136adb776a7530995416c59254b9453ac038
    
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: 7wesley/cards-frontend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
<<<<<<< HEAD
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  build-publish-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: 7wesley/cards-backend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
=======
        password: ${{ secrets.DOCKER_PASSWORD }}
>>>>>>> 7582136adb776a7530995416c59254b9453ac038
